### PR TITLE
Update 1.3.0 dependencies & enable pip check for testing and greyskull updating

### LINKED ISSUE #25: Incorrect dependencies for v1.3.0
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The requirements for this package in conda-forge do not match those of the `requirements/install.pip` file in the Github repo.  There are several significant changes from v1.2.0 (like flask v3 support).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

### PR DESCRIPTION
**Pull request by DManowitz**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Fixes #25

### CODE REVIEW

**Comment by DManowitz** [comment]
@conda-forge-admin, please rerender

**Comment by samirelanduk** [comment]
Could this be merged? flask-restx cannot currently be used with Flask 3 when installing via conda, because the conda recipe has `Flask >=0.8,!=2.0.0,<3` (which this PR will fix).

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Review by fhoehle — APPROVED** [review]

**Comment by fhoehle** [comment]
thanks @samirelanduk for reminding me

**Pull request merged**
